### PR TITLE
feat: redesign overview page

### PR DESCRIPTION
**Pull request by guerrap**
# Summary

Related to #93.

Redesign of the `overview` page, following the new Figma mockups.
Done:
- [x] `volume` and `liquidity` charts
- [x] `top tokens`, `top pairs` and `transaction` lists
- [x] Adapt mobile view

Chart section before:
image
Chart section after:
image

List before:
image
List after:
image

# How To Test
1.  Open the page `overview`
- [ ] Verify the design matches the one on Figma

### CODE REVIEW

**Comment by wixzi** [comment]
Screenshot 2022-07-30 at 22 01 08
These prices and percentage is little off I feel. @0xVenky ?

**Review by wixzi — DISMISSED** [review]
Code looks ok to merge.

**Comment by guerrap** [comment]
> Screenshot 2022-07-30 at 22 01 54
> 
> These prices and percentages is little off I feel. @0xVenky ?

What do you mean by off?

**Comment by 0xVenky** [comment]
> > Screenshot 2022-07-30 at 22 01 54
> > 
> > These prices and percentages is little off I feel. @0xVenky ?
> 
> What do you mean by off?

Dont they all look the same :)

**Comment by velusgautam** [comment]
@guerrap from where we fetch the price? And how frequently we update it. Since eth price was not the live price I checked

**Review by luzzif — APPROVED** [review]

**Pull request merged**
